name: ci
on:
  push:
    branches: ['*']
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22, 24]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: ${{ matrix.node }}
      - run: yarn --frozen-lockfile
      - run: yarn tsc --noEmit
      - run: yarn prettier --check .
      - run: yarn lint
      - run: yarn flow
      - working-directory: example/
        run: |
          yarn --frozen-lockfile
          yarn test
  build-android-oldarch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.8
      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - working-directory: android/
        run: gradle build
  build-android-newarch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.8
      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - env:
          _JAVA_OPTIONS: -Xmx4096m -XX:MaxMetaspaceSize=1024m
          ORG_GRADLE_PROJECT_newArchEnabled: true
        working-directory: android/
        run: gradle build
  build-ios-oldarch:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: curl https://raw.githubusercontent.com/fbtmp/rn-native-module-support/41457158a0b37abd522bd10d1f0b434daadbe797/Podfile -o ios/Podfile
      - uses: actions/cache@v4
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-oldarch-${{ hashFiles('ios/Podfile') }}
          restore-keys: |
            ${{ runner.os }}-pods-oldarch-
      - working-directory: ios/
        run: pod install
      - run: xcodebuild -workspace "ios/RNLinearGradient.xcworkspace" -scheme "RNLinearGradient" -sdk iphonesimulator
  build-ios-newarch:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: curl https://raw.githubusercontent.com/fbtmp/rn-native-module-support/41457158a0b37abd522bd10d1f0b434daadbe797/Podfile -o ios/Podfile
      - uses: actions/cache@v4
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-newarch-${{ hashFiles('ios/Podfile') }}
          restore-keys: |
            ${{ runner.os }}-pods-newarch-
      - working-directory: ios/
        run: RCT_NEW_ARCH_ENABLED=1 pod install
      - run: xcodebuild -workspace "ios/RNLinearGradient.xcworkspace" -scheme "RNLinearGradient" -sdk iphonesimulator
  integration-rn72:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: 20
      - run: echo "y" | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager "ndk;23.1.7779620"
      - run: yarn --frozen-lockfile
      - run: npx react-native@0.72.17 init rn72 --version 0.72.17 --skip-install
      - working-directory: rn72/
        run: |
          yarn
          yarn add link:./..
      - working-directory: rn72/android/
        run: |
          echo "ndk.dir=${ANDROID_SDK_ROOT}/ndk/23.1.7779620" > local.properties
          echo "android.enableJetifier=false" >> gradle.properties
          ./gradlew build
